### ISSUE TITLE
Persist plugin location after refresh (not just restart)

### ISSUE THREAD

**Issue by oleander** [oleander/bitbar#9]
- Original issues
  - matryer/bitbar#416
  - matryer/bitbar#387
  - matryer/bitbar#341 (example)
  - matryer/bitbar#241

**Comment by dkvdm** [comment]
I've been using your fork, and I'd love to see Bitbar keep its plugin location persist!

**Comment by danielsatanik** [comment]
@oleander I tried using your plugin, but it seems I cannot show base64 encoded images as I can with the original, but I would like to use your fork because it is more up-to-date and seems to keep the icon location in the menubar, anything I have to do different than in the original?
